[package]
name = "line_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = ">=0.2.0"
winit = ">=0.27.5"
pixel_lib = {path = "../pixel_lib"}
